services:
  # 基础设施服务
  mysql:
    image: mysql:8
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: 20040412mzq
      MYSQL_DATABASE: ecommerce_order_db
    ports:
      - "3306:3306"
    volumes:
      - ./java-services/.mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos-test
    ports:
      - "8848:8848"
    volumes:
      - ./java-services/.nacos-data:/home/nacos/data
    networks:
      - backend
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/Shanghai

  redis:
    image: redis:6
    container_name: redis-test
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./java-services/.redis-data:/data

  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - backend
    volumes:
      - ./java-services/data/ES_products.csv:/data/ES_products.csv

  es-init:
    image: python:3.11-alpine
    container_name: es-init
    depends_on:
      - elasticsearch
    networks:
      - backend
    volumes:
      - ./java-services/data/ES_products.csv:/data/ES_products.csv:ro
      - ./java-services/es_import.py:/es_import.py:ro
    entrypoint:
      - sh
      - -c
      - |
        pip install requests
        python /es_import.py

networks:
  backend:
    driver: bridge