server:
  port: 8083 # order-service 运行在 8083 端口

spring:
  application:
    name: order-service
  cloud: # Nacos 服务发现配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 你的Nacos服务器地址

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 20040412mzq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true