services:
  mysql:
    image: mysql:8
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: 20040412mzq
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
    restart: always
    networks:
      - backend

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos-test
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - backend
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_HOST=mysql-test
      - MYSQL_MASTER_PORT=3306
      - MYSQL_MASTER_USER=root
      - MYSQL_MASTER_PASSWORD=20040412mzq
      - MYSQL_MASTER_DB_NAME=nacos_config
      - TZ=Asia/Shanghai

  redis:
    image: redis:6
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - backend

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - mysql
      - nacos

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - redis
      - nacos

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - elasticsearch
      - nacos
  services-gateway:
    build:
      context: ./services-gateway
    container_name: services-gateway
    ports:
      - "8084:8084"
    depends_on:
      - nacos
      - order-service
      - product-service
      - payment-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
