services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: mysql-test # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: Longquan1 # root 用户密码
      MYSQL_DATABASE: ecommerce_order_db
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
    networks:
      - backend
    restart: always # 崩溃后自动重启
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos-test
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - backend
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
  redis:
    image: redis:6
    container_name: redis-test
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./.redis-data:/data # 持久化
  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - backend
    volumes:
      - ./data/ES_products.csv:/data/ES_products.csv

  es-init:
    image: python:3.11-alpine
    container_name: es-init
    depends_on:
      - elasticsearch
    networks:
      - backend
    volumes:
      - ./data/ES_products.csv:/data/ES_products.csv:ro
      - ./es_import.py:/es_import.py:ro
    entrypoint:
      - sh
      - -c
      - |
        pip install requests
        python /es_import.py

networks:
  backend:
    driver: bridge