
services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-test:3306/ecommerce_order_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "20040412mzq"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR: "nacos-test:8848"
    networks:
      - backend

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      SPRING_REDIS_HOST: "redis-test"
      SPRING_REDIS_PORT: "6379"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR: "nacos-test:8848"
    networks:
      - backend

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_ELASTICSEARCH_URIS: "http://elasticsearch-test:9200"
    networks:
      - backend

  service-gateway:
    build:
      context: ./services-gateway
      dockerfile: Dockerfile
    container_name: services-gateway
    ports:
      - "8084:8084"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR: "nacos:8848"
    networks:
      - backend

networks:
  backend:
    driver: bridge
