services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - nacos
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ecommerce_order_db?useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Longquan1"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR: "nacos:8848"
    networks:
      - backend

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - nacos
    environment:
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR: "nacos:8848"
    networks:
      - backend

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - elasticsearch
    environment:
      SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
    networks:
      - backend

networks:
  backend:
    driver: bridge
