server:
  port: 8081

spring:
  application:
    name: payment-service

  data:
    redis:
      host: redis
      port: 6379
      # password: （留空表示无密码）

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

alipay:
  appId: 9021000150621526
  appPrivateKey: MIIEvQIB...
  alipayPublicKey: MIIBIjANBgkqh...
  notifyUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
