server:
  port: 8081

spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848
  redis:
    host: localhost
    port: 6379
    password: