spring:
  application:
    name: services-gateway
  cloud:
    gateway:
      server:
        webflux:  # ?? webflux ??
          routes:
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1

            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1

            - id: payment-service
              uri: http://localhost:8081
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8084